# Mainnet
L1 = ["https://eth.merkle.io", 'https://eth.llamarpc.com', 'https://rpc.mevblocker.io', 'https://eth.drpc.org', 'https://rpc.payload.de', 'https://eth.blockrazor.xyz']
base = ["https://base.llamarpc.com", 'https://base-rpc.publicnode.com', 'https://1rpc.io/base', 'https://base-pokt.nodies.app']
arbitrum = ['https://rpc.therpc.io/arbitrum', 'https://1rpc.io/arb', 'https://arb-pokt.nodies.app', 'https://arbitrum.meowrpc.com', 'https://arb-pokt.nodies.app', 'https://rpc.therpc.io/arbitrum', 'https://arb-pokt.nodies.app']
optimism = ['https://1rpc.io/op', 'https://optimism-rpc.publicnode.com', 'https://optimism.drpc.org']
soneium = ['https://rpc.soneium.org']
Polygon = ['https://1rpc.io/matic']
Binance_Smart_Chain = ['https://bsc.meowrpc.com']
Avalanche = ['https://avax-pokt.nodies.app/ext/bc/C/rpc', 'https://avax.meowrpc.com', 'https://1rpc.io/avax/c']
Fantom = ['https://fantom.drpc.org', 'https://fantom-pokt.nodies.app', 'https://rpcapi.fantom.network']
Gravity_Alpha_Mainnet = ['https://rpc.gravity.xyz', 'https://rpc.ankr.com/gravity']
zora = ['https://rpc.zora.energy']
Abstract = ['https://api.mainnet.abs.xyz']

# Testnets
sepolia = ['https://1rpc.io/sepolia']
monad_testnet = ['https://testnet-rpc.monad.xyz']
sahara_testnet = ['https://testnet.saharalabs.ai']
somnia_testnet = ['https://dream-rpc.somnia.network']
mega_eth_testnet = ['https://carrot.megaeth.com/rpc']
pharos_testnet = ['https://testnet.dplabs-internal.com']
camp_testnet = ['https://rpc-campnetwork.xyz']